### ISSUE TITLE
Can I somehow disable remote requests?

### ISSUE THREAD

**Issue by Termina1** [uber/eight-track#36]
I want to create fixtures on my local machine, and do not create them on CI server (use saved fixtures from repo). So, basically I want to disable recording during CI run. Is it possible now?

**Comment by twolfson** [comment]
Currently, there is no way to disable recording of fixtures. We could probably add an option like `preventRecording` which you can enable based on the CI environment variables:

```js
eightTrack({
  url: 'http://localhost:1337',
  fixtureDir: 'fixtures/',
  // Coerce TRAVIS environment flag to boolean (e.g. "true" -> `true`, "" -> `false`)
  preventRecording: !!process.env.TRAVIS
});
```

This would emit errors on `localReq` as we do with any file-system related errors:

https://github.com/uber/eight-track/blob/2.1.0/lib/eight-track.js#L218-L219

**Comment by twolfson** [comment]
This feature will likely be built on my fork of `eight-track` (`nine-track`):

https://github.com/twolfson/nine-track

I will take a look at implementing it by the end of this weekend.

**Comment by Termina1** [comment]
@twolfson ok, thanks, will move to your fork then

**Comment by twolfson** [comment]
`preventRecording` has been added in `nine-track@1.4.0`

**Comment by Termina1** [comment]
@twolfson works great, thank you
